### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by pepf** [WhitestormJS/whitestorm-app-boilerplate#1]
I like the idea of having a boilerplate, but I can't really figure out how to use it.
For example, how to add physics in this sample scenario?

Syntax that I find on other websites about whitestorm doesn't match the syntax used in the boilerplate, so thus far I wasn't able to customise this example to fit my needs.

**Comment by sasha240100** [comment]
@perf Yep, we use v2.x.x beta in this repo. To add physics, simply include `physics-ammonext-module` dependency to your app file and get some modules from it.

`import {WorldModule, SphereModule} from 'physics-ammonext-module';`

Then use them as written in whitestorm.js readme

**Comment by sasha240100** [comment]
http://codepen.io/sasha240100/pen/wgEXwN
