### ISSUE TITLE
Warning: ExtrudeBufferGeometry was not found

### ISSUE THREAD

**Issue by hirako2000** [WhitestormJS/whitestorm-app-boilerplate#11]
no impact, but the console shows this warning:
```./~/whs/src/components/meshes/Extrude.js```
```50:59-80 export 'ExtrudeBufferGeometry' was not found in 'three'```

**Comment by sasha240100** [comment]
@hirako2000 [This line](https://github.com/WhitestormJS/whitestorm.js/blob/beta/src/components/meshes/Extrude.js#L42) should be rewritten.

**Comment by hirako2000** [comment]
ok, I will fix this.

**Comment by hirako2000** [comment]
looks right?

```
  buildGeometry(params = {}) {
    const extrudeGeometry = new ExtrudeGeometry(
      params.geometry.shapes,
      params.geometry.options
    );

    return params.buffer && !params.softbody ? new BufferGeometry().fromGeometry(extrudeGeometry) : extrudeGeometry;
  }
```

**Comment by sasha240100** [comment]
@hirako2000  yes! good.

**Comment by sasha240100** [comment]
Issue moved to https://github.com/WhitestormJS/whitestorm.js/issues/237
