### ISSUE TITLE
Issues running boilerplate

### ISSUE THREAD

**Issue by tpflueger** [WhitestormJS/whitestorm-app-boilerplate#2]
I recently cloned the project but ran into issues with not having whitestorm and webpack-dev-server installed. Webpack also got upset with wanting an absolute output path.

**Comment by sasha240100** [comment]
@tpflueger You need to do `npm install`

**Comment by tpflueger** [comment]
@sasha240100 I've done that, but I'm still running into the issues described.

Currently using node@7.5 and npm@4.1.2.

**Comment by sasha240100** [comment]
@tpflueger Okay, I checked `package.json`. It seems I forgot to add them there. I'll fix it later today, if you can make a pull request - do it, I'll merge immediately.
Thanks!
