### ISSUE TITLE
First Person Controls?

### ISSUE THREAD

**Issue by jlieb10** [WhitestormJS/whitestorm-app-boilerplate#4]
Hey, I see first person controls as a WIP in the docs but can't find any reference to the code that's in progress in this repo or the whitestorm.js repo- happy to contribute, but would be nice to see what stage it's at now.  Thanks!

**Comment by sasha240100** [comment]
@jlieb10 Sorry, not yet well-documented. And the link to FPS controls:
https://github.com/WhitestormJS/physics-module-ammonext/blob/master/src/modules/controls/FirstPersonModule.js

It's now in physics repo.
