### ISSUE TITLE
the url of model is error

### ISSUE THREAD

**Issue by elva2596** [WhitestormJS/whitestorm-app-boilerplate#8]
the url of model is error：bundle.js:2140  GET http://localhost:8080/assets/models/GlassPlate.obj 404 (Not Found)

`GlassPlate.obj`  is under app/assets/models;

`app/components/BasicComponent.js`：

```
const teapot = new Model({
  geometry: {
    path: "../assets/models/GlassPlate.obj"
  },
  pos: {
    x: 0,
    y: 5,
    z: 0
  },
  scale: {
    x: 4,
    y: 4,
    z: 4
  }
});

```

when I move `teapot-claraio.json` to build file ,the error is disappear；but when I app.add(teopot), the error is : THREE.JSONLoader: ../build/teapot-claraio.json should be loaded with THREE.ObjectLoader instead. then I change params of loader to new THREE.ObjectLoader

```
const teapot = new Model({
  geometry: {
    path: "../build/GlassPlate.obj",
    loader:new THREE.OBJLoader()
  },
  pos: {
    x: 0,
    y: 5,
    z: 0
  },
  scale: {
    x: 4,
    y: 4,
    z: 4
  }
});

```

`when I app.add(teopot)`;
app.js：

```
import {App} from '@whs/core/App';
import {plane,light,box,teapot} from './components/BasicComponent';
import {elementModule,cameraModule,sceneModule,renderModule,orbitModule,resizeModule} from './modules/BasicModule'
const app = new App([elementModule,sceneModule,cameraModule,renderModule,orbitModule,resizeModule]);
app.add(plane)
app.add(light)
console.log(teapot);
// console.log(plane);
// app.add(teapot)
app.start()
```

the value of console.log(teopot) is Model, but the error is 

```

:8080/build/bundle.js:605 Uncaught TypeError: Cannot read property 'center' of undefined
    at Sphere.copy (:8080/build/bundle.js:605)
    at isObjectViewable (:8080/build/bundle.js:1255)
    at projectObject (:8080/build/bundle.js:1256)
    at projectObject (:8080/build/bundle.js:1256)
    at WebGLRenderer.render (:8080/build/bundle.js:1241)
    at Loop.func (:8080/build/bundle.js:7716)
    at Loop.execute (:8080/build/bundle.js:6428)
    at App.process (:8080/build/bundle.js:9520)

```

how to solve?

**Comment by sasha240100** [comment]
@elva2596 hah, sorry, git failed to commit model)

**How to solve:**
At first - what you did with loader is right. To ensure what type of content you receive from loader - you should also add a `parser()` function:

```javascript
const model = new WHS.Model({
  geometry: {
    // ...

    loader: new THREE.ObjectLoader(),

    parser(...input) { // geometry, material for example. Depends on loader
      // ...
      return new THREE.Mesh(); // This will be your .native
    }
  }
  
   // ...
};
```

`parser` receives exported data as arguments (can be many) and then should return a mesh.

**Debugging**

```javascript
const model = new WHS.Model({
  geometry: {
    // ...

    loader: new THREE.ObjectLoader(),

    parser(...input) { // geometry, material for example. Depends on loader
      // ...
      console.log(input); // if `undefined` - then something wrong with path/loader/file
      debugger;
    }
  }
  
   // ...
};
```

**Comment by elva2596** [comment]
hello, accoding to the example, my code is 


```
const teapot = new WHS.Model({
  geometry: {
    path: "../build/utah-teapot-large.json",
    parser(...input) { // geometry, material for example. Depends on loader
      // ...
       return new THREE.Mesh(input[0]); // if `undefined` - then something wrong with path/loader/file
      
      // debugger;
    }
  },

  material: new THREE.MeshLambertMaterial({
    vertexColors: THREE.VertexColors,
    shading: THREE.SmoothShading,
    side: THREE.DoubleSide
  }),
  modules: [
    new WHS.mesh.TextureModule({
      url: '../build/teapot.jpg'
    })
  ],
    
  useCustomMaterial: true, // Required if you want to force the use of material you provide
  pos: {
    x: 0,
    y: 100,
    z: 0
  },
  scale: {
    x: 4,
    y: 4,
    z: 4
  }
});
const light = new DirectionalLight({
    light: {
    color: 0xff0000
  },
  position: [10, 20, 10]
})
```

when I add the `parser` function ,there are no errors in controls.I can see teopot in white color. but `WHS.mesh.TextureModule`  is not  usful. and the  param of input  `is [Geometry,undefined]` why the second item is undefined?
my code is [here](https://github.com/elva2596/whs)

**Comment by sasha240100** [comment]
@elva2596 because it seems that you model exports only geometry.

Use of `TextureModule` seems fine to me. I don't see any reason of why it shouldn't work. But, if you say that your teapot is white, it is white as lambert material?

Also note that `pos` will not work. Replace with `position`

**Comment by elva2596** [comment]
I try it once again,is it a bug?when i load my `.obj` model and my `png` texture, the color of model is not modified. It should be this [style](https://github.com/elva2596/whs/blob/master/assets/yanshi.png).why is it?


my code is [here](https://github.com/elva2596/whs/blob/master/app/components/BasicComponent.js)

**Comment by sasha240100** [comment]
@elva2596 Thanks for providing the code! I will check later today. (Please ping me discord chat for fast response next time, I can miss some msgs in GitHub)

**Comment by elva2596** [comment]
hello, Could you please help me review my code by convenience? Thank you

**Comment by sasha240100** [comment]
@elva2596 Will do. Can you contact me in [discord](https://discordapp.com/invite/frNetGE)?

**Comment by sasha240100** [comment]
@elva2596 What [this line](https://github.com/elva2596/whs/blob/master/app/components/BasicComponent.js#L30) returns? Answer me in discord.

**Comment by elva2596** [comment]
ok no problem

**Comment by hirako2000** [comment]
fixed? can we close?
